disabled_rules:
  - trailing_whitespace
  - force_cast
  - mark

opt_in_rules:
  - force_unwrapping
  - closure_spacing
  - empty_count
  - fatal_error_message

analyzer_rules:
  - explicit_self

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - TV

identifier_name:
  allowed_symbols: ["_"]
  excluded:
    - id
    - tv
    - tmdb

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 10
  error: 20

file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true

reporter: xcode

included:
  - CinemarkApp

excluded:
  - Pods
  - Carthage
  - CinemarkAppTests
  - Scripts
