name: CI
    
on:
  push:
    branches: [ feature/ci-action ]
  pull_request:
    branches: [ feature/ci-action ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Install Dependencies
        run: |
          brew install swiftlint
          sudo gem install xcpretty

      - name: Resolve Package Dependencies
        run: |
            xcodebuild -project CinemarkApp/CinemarkApp.xcodeproj -resolvePackageDependencies

      - name: Build and Test
        run: |
          set -o pipefail && \
          xcodebuild clean build \
          -project CinemarkApp/CinemarkApp.xcodeproj \
          -scheme CinemarkApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty

